import type { Metadata } from 'next'

import './global.css'

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='p-12'>
      <body>{children}</body>
    </html>
  )
}
